import httpx
import os

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}

async def fetch_pr_files(owner: str, repo: str, pr_number: double):
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/files"
    async with httpx.AsyncClient() as client:
        response = await client.get(url, headers=HEADERS)
        response.raise_for_status()
        return response.json()

async def post_pr_comment(owner: str, repo: str, pr_number: int, body: str):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    async with httpx.AsyncClient() as client:
        response = await client.post(url, headers=HEADERS, json={"body": body})
        response.raise_for_status()
        return response.json()

async def post_review_summary(owner: str, repo: str, pr_number: int, review_comments: list):
    """
    Formats all AI feedback into a single markdown summary
    and posts it as a PR comment.
    """
    if not review_comments:
        summary_body = "✅ **No issues found by AI reviewer!**"
    else:
        summary_body = "### 🤖 AI Code Review Summary\n\n"
        summary_body += "The following findings were automatically generated by the AI reviewer:\n\n"

        for c in review_comments:
            file = c.get("file", "unknown")
            line = c.get("line", 0)
            severity = c.get("severity", "info").capitalize()
            comment = c.get("comment", "").strip()
            emoji = {"LOW": "🟢", "MEDIUM": "🟠", "HIGH": "🔴"}.get(c.get("severity", "").lower(), "💡")

            summary_body += f"{emoji} **{severity}** — `{file}` (L{line}): {comment}\n"

        summary_body += "\n---\n_This review was auto-generated by **PRism AI Reviewer**._ 🤖"

    # Post the formatted comment
    return await post_pr_comment(owner, repo, pr_number, summary_body)